AWSTemplateFormatVersion: "2010-09-09"
Description: Teste

Resources:
  LogsStackTeste:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub:
          - "./log/log-group.yaml"
          - StageName: !Ref StageName

Parameters:
  StageName:
    Type: String
    Description: Nome do bucket
