AWSTemplateFormatVersion: "2010-09-09"
Description: Teste

Resources:
  LogsStackTeste:
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: "https://testebucketpipeline.s3.amazonaws.com/log/log-group.yaml"
