AWSTemplateFormatVersion: "2010-09-09"
Description: Teste

Resources:
  LogsStackTeste:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: log-group.yaml

Parameters:
  StageName:
    Type: String
    Description: Nome do bucket
