AWSTemplateFormatVersion: "2010-09-09"
Description: Teste

Resources:
  TesteBucketPipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "testebucketpipeline-${StageName}"

  TesteBucketPipelinePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TesteBucketPipelineBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowListBucket
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "s3:ListBucket"
            Resource: !Sub "arn:aws:s3:::${TesteBucketPipelineBucket}"
            Condition: {}
          - Sid: AllowPutObject
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${TesteBucketPipelineBucket}/*"
            Condition: {}

Parameters:
  StageName:
    Type: String
    Description: Nome do bucketttttt
