name: ci-workflow-teste
on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-go: ["1.15", "1.16"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Seta variável de ambiente
        run: |
          if [[ "$GITHUB_BASE_REF" == "master" ]]; then
            echo "DEPLOY_ENV=PROD" >> $GITHUB_ENV
          elif [[ "$GITHUB_BASE_REF" == "staging" ]]; then
            echo "DEPLOY_ENV=STAGING" >> $GITHUB_ENV
          fi


          echo ${{secrets}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', env.DEPLOY_ENV)] }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', env.DEPLOY_ENV)] }}
          aws-region: ${{ secrets[format('AWS_REGION_{0}', env.DEPLOY_ENV)] }}

      - name: Checa se existe o bucket que irá alocar os itens
        id: stack_first_bucket_exists
        run: |
          if aws cloudformation describe-stacks --stack-name ${{ format('BUCKET_SETUP_{0}', env.DEPLOY_ENV) }}; then
            echo "stack_first_bucket_exists=true" >> $GITHUB_ENV
          else
            echo "stack_first_bucket_exists=false" >> $GITHUB_ENV
          fi

      - name: Roda o comando pra atualizar ou criar a pilha
        run: |
          if [ "${{ env.stack_first_bucket_exists }}" = "true" ]; then
            echo "Updating existing stack"
            aws cloudformation update-stack \
              --stack-name ${{ format('BUCKET_SETUP_{0}', env.DEPLOY_ENV) }} \
              --template-body file://setup/bucket-role.yaml \
              --parameters ParameterKey=StageName, ParameterValue=${{ env.DEPLOY_ENV }} \
              --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
          else
            echo "Creating new stack"
            aws cloudformation create-stack \
              --stack-name ${{ format('BUCKET_SETUP_{0}', env.DEPLOY_ENV) }} \
              --template-body file://setup/bucket-role.yaml \
              --parameters ParameterKey=StageName, ParameterValue=${{ env.DEPLOY_ENV }} \
              --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
          fi

      - name: Cria pasta 'log' caso ela não exista
        run: |
          if ! aws s3api list-objects-v2 --bucket your-bucket-name --prefix log/ | grep -q 'Contents'; then
            aws s3api put-object --bucket your-bucket-name --key log/
          fi
      - name: Faz o upload dos arquivos
        run: |
          aws s3 cp ../../log/log-group.yaml s3://testebucketpipeline-${{ env.DEPLOY_ENV }}/log/ --recursive

      - name: Checa se existe a pilha do cloudformation
        id: stack_exists
        run: |
          if aws cloudformation describe-stacks --stack-name teste-pilha-${{ env.DEPLOY_ENV }}; then
            echo "stack_exists=true" >> $GITHUB_ENV
          else
            echo "stack_exists=false" >> $GITHUB_ENV
          fi

      - name: Roda o comando pra atualizar ou criar a pilha
        run: |
          if [ "${{ env.stack_exists }}" = "true" ]; then
            echo "Updating existing stack"
            aws cloudformation update-stack \
              --stack-name teste-pilha-${{ env.DEPLOY_ENV }} \
              --template-body file://template.yaml \
              --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
          else
            echo "Creating new stack"
            aws cloudformation create-stack \
              --stack-name teste-pilha-${{ env.DEPLOY_ENV }} \
              --template-body file://template.yaml \
              --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
          fi
